create table if not exists public.realtor_listings (
    id bigint generated by default as identity primary key,
    url text not null unique,
    address text,
    price text,
    bedrooms integer,
    bathrooms integer,
    results_page integer,
    listing_description text,
    property_type text,
    building_type text,
    square_feet text,
    land_size text,
    built_in text,
    annual_taxes text,
    hoa_fees text,
    time_on_realtor text,
    zoning_type text,
    search_criteria jsonb not null default '{}'::jsonb,
    scrape_limits jsonb not null default '{}'::jsonb,
    raw_listing jsonb not null default '{}'::jsonb,
    last_scraped_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists realtor_listings_set_updated_at on public.realtor_listings;

create trigger realtor_listings_set_updated_at
before update on public.realtor_listings
for each row
execute function public.set_updated_at();
