create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.saved_searches (
    id bigint generated by default as identity primary key,
    search_key text not null unique,
    name text not null,
    location text not null,
    min_price integer,
    max_price integer,
    beds_min integer,
    property_type text,
    -- search_snapshot.buy_box stores the persisted buy-box settings for this search
    search_snapshot jsonb not null default '{}'::jsonb,
    last_scraped_at timestamptz,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.scrape_runs (
    id bigint generated by default as identity primary key,
    saved_search_id bigint not null references public.saved_searches(id) on delete cascade,
    status text not null,
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    results_count integer,
    summary_count integer not null default 0,
    detail_attempted integer not null default 0,
    detail_succeeded integer not null default 0,
    failed_detail_urls jsonb not null default '[]'::jsonb,
    error_message text,
    search_snapshot jsonb not null default '{}'::jsonb,
    run_settings jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.listings (
    id bigint generated by default as identity primary key,
    source text not null default 'realtor.ca',
    source_listing_key text not null unique,
    url text not null unique,
    address text,
    price text,
    bedrooms integer,
    bathrooms integer,
    listing_description text,
    property_type text,
    building_type text,
    square_feet text,
    land_size text,
    built_in text,
    annual_taxes text,
    hoa_fees text,
    time_on_realtor text,
    zoning_type text,
    raw_listing jsonb not null default '{}'::jsonb,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    last_scraped_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.scrape_run_listings (
    id bigint generated by default as identity primary key,
    scrape_run_id bigint not null references public.scrape_runs(id) on delete cascade,
    saved_search_id bigint not null references public.saved_searches(id) on delete cascade,
    listing_id bigint not null references public.listings(id) on delete cascade,
    results_page integer,
    is_new_in_run boolean not null default false,
    raw_listing_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (scrape_run_id, listing_id)
);

create table if not exists public.saved_search_listings (
    id bigint generated by default as identity primary key,
    saved_search_id bigint not null references public.saved_searches(id) on delete cascade,
    listing_id bigint not null references public.listings(id) on delete cascade,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    first_seen_run_id bigint references public.scrape_runs(id) on delete set null,
    last_seen_run_id bigint references public.scrape_runs(id) on delete set null,
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (saved_search_id, listing_id)
);

create table if not exists public.saved_search_investment_defaults (
    id bigint generated by default as identity primary key,
    saved_search_id bigint not null unique references public.saved_searches(id) on delete cascade,
    defaults_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.listing_investment_overrides (
    id bigint generated by default as identity primary key,
    saved_search_id bigint not null references public.saved_searches(id) on delete cascade,
    listing_id bigint not null references public.listings(id) on delete cascade,
    overrides_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (saved_search_id, listing_id)
);

create table if not exists public.market_reference_data (
    id bigint generated by default as identity primary key,
    source text not null,
    source_dataset text,
    market_name text not null,
    province text,
    market_key text not null,
    geography_type text,
    property_type text,
    bedroom_count integer,
    average_rent_monthly numeric,
    vacancy_rate_percent numeric,
    source_url text,
    source_date date,
    raw_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.saved_search_market_matches (
    id bigint generated by default as identity primary key,
    saved_search_id bigint not null unique references public.saved_searches(id) on delete cascade,
    market_reference_id bigint references public.market_reference_data(id) on delete set null,
    match_type text not null,
    matched_market_name text,
    match_notes text,
    confidence text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.ai_underwriting_suggestions (
    id bigint generated by default as identity primary key,
    saved_search_id bigint not null references public.saved_searches(id) on delete cascade,
    listing_id bigint references public.listings(id) on delete cascade,
    suggestion_type text not null,
    status text not null,
    prompt_text text not null,
    model text,
    input_context jsonb not null default '{}'::jsonb,
    raw_response_text text,
    parsed_suggestion jsonb not null default '{}'::jsonb,
    accepted_value numeric,
    accepted_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists scrape_runs_saved_search_started_idx
on public.scrape_runs(saved_search_id, started_at desc);

create index if not exists scrape_run_listings_saved_search_idx
on public.scrape_run_listings(saved_search_id, scrape_run_id);

create index if not exists scrape_run_listings_listing_idx
on public.scrape_run_listings(listing_id);

create index if not exists saved_search_listings_saved_search_active_idx
on public.saved_search_listings(saved_search_id, is_active);

create index if not exists market_reference_market_key_idx
on public.market_reference_data(market_key);

create index if not exists market_reference_lookup_idx
on public.market_reference_data(market_key, property_type, bedroom_count);

drop trigger if exists saved_searches_set_updated_at on public.saved_searches;
create trigger saved_searches_set_updated_at
before update on public.saved_searches
for each row
execute function public.set_updated_at();

drop trigger if exists listings_set_updated_at on public.listings;
create trigger listings_set_updated_at
before update on public.listings
for each row
execute function public.set_updated_at();

drop trigger if exists saved_search_listings_set_updated_at on public.saved_search_listings;
create trigger saved_search_listings_set_updated_at
before update on public.saved_search_listings
for each row
execute function public.set_updated_at();

drop trigger if exists saved_search_investment_defaults_set_updated_at on public.saved_search_investment_defaults;
create trigger saved_search_investment_defaults_set_updated_at
before update on public.saved_search_investment_defaults
for each row
execute function public.set_updated_at();

drop trigger if exists listing_investment_overrides_set_updated_at on public.listing_investment_overrides;
create trigger listing_investment_overrides_set_updated_at
before update on public.listing_investment_overrides
for each row
execute function public.set_updated_at();

drop trigger if exists market_reference_data_set_updated_at on public.market_reference_data;
create trigger market_reference_data_set_updated_at
before update on public.market_reference_data
for each row
execute function public.set_updated_at();

drop trigger if exists saved_search_market_matches_set_updated_at on public.saved_search_market_matches;
create trigger saved_search_market_matches_set_updated_at
before update on public.saved_search_market_matches
for each row
execute function public.set_updated_at();

create or replace view public.current_active_saved_search_listings as
select
    ss.id as saved_search_id,
    ss.search_key,
    ss.name as saved_search_name,
    ssl.last_seen_run_id as scrape_run_id,
    sr.finished_at as run_finished_at,
    l.id as listing_id,
    l.source,
    l.source_listing_key,
    l.url,
    l.address,
    l.price,
    l.bedrooms,
    l.bathrooms,
    l.listing_description,
    l.property_type,
    l.building_type,
    l.square_feet,
    l.land_size,
    l.built_in,
    l.annual_taxes,
    l.hoa_fees,
    l.time_on_realtor,
    l.zoning_type,
    ssl.first_seen_at,
    ssl.last_seen_at,
    ssl.is_active,
    l.last_scraped_at,
    srl.results_page,
    srl.is_new_in_run
from public.saved_search_listings ssl
join public.saved_searches ss on ss.id = ssl.saved_search_id
join public.listings l on l.id = ssl.listing_id
left join public.scrape_runs sr on sr.id = ssl.last_seen_run_id
left join public.scrape_run_listings srl
    on srl.scrape_run_id = ssl.last_seen_run_id
   and srl.saved_search_id = ssl.saved_search_id
   and srl.listing_id = ssl.listing_id
where ssl.is_active = true;
