from __future__ import annotations

from typing import Any


MARKET_PROFILES: list[dict[str, Any]] = [
    {
        "market_key": "vancouver_bc",
        "market_name": "Vancouver",
        "province": "BC",
        "geography_type": "cma",
        "status": "active",
        "notes": "First-pass structured market context seeded from official Statistics Canada pages. CMHC housing fundamentals are read separately from market_reference_data.",
    },
    {
        "market_key": "victoria_bc",
        "market_name": "Victoria",
        "province": "BC",
        "geography_type": "cma",
        "status": "active",
        "notes": "First-pass structured market context seeded from official Statistics Canada pages. CMHC housing fundamentals are read separately from market_reference_data.",
    },
    {
        "market_key": "duncan_bc",
        "market_name": "Duncan",
        "province": "BC",
        "geography_type": "ca",
        "status": "active",
        "notes": "First-pass structured market context seeded from official Statistics Canada pages. CMHC housing fundamentals currently use the explicit Victoria proxy already defined in the app.",
    },
    {
        "market_key": "sidney_bc",
        "market_name": "Sidney",
        "province": "BC",
        "geography_type": "csd",
        "status": "active",
        "notes": "First-pass structured market context seeded from official Statistics Canada pages for the Town of Sidney. CMHC housing fundamentals are not yet available as exact structured rows in market_reference_data.",
    },
]


MARKET_METRICS: list[dict[str, Any]] = [
    {
        "market_key": "vancouver_bc",
        "metric_key": "population",
        "value_numeric": 2642825,
        "unit": "people",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/details/page.cfm?DGUIDlist=2021S0503933&GENDERlist=1&HEADERlist=0&Lang=E&STATISTIClist=1",
        "confidence": "high",
        "notes": "Vancouver CMA population in the 2021 Census.",
    },
    {
        "market_key": "vancouver_bc",
        "metric_key": "population_growth_percent",
        "value_numeric": 7.3,
        "unit": "percent",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/details/page.cfm?DGUIDlist=2021S0503933&GENDERlist=1&HEADERlist=0&Lang=E&STATISTIClist=1",
        "confidence": "high",
        "notes": "Population change from 2016 to 2021 for Vancouver CMA.",
    },
    {
        "market_key": "vancouver_bc",
        "metric_key": "unemployment_rate_percent",
        "value_numeric": 8.6,
        "unit": "percent",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/as-sa/fogs-spg/page.cfm?dguid=2021S0503933&lang=E&topic=12",
        "confidence": "medium",
        "notes": "Census unemployment rate for the population aged 15+ in Vancouver CMA.",
    },
    {
        "market_key": "vancouver_bc",
        "metric_key": "median_household_income",
        "value_numeric": 79500,
        "unit": "cad",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/details/page.cfm?DGUIDlist=2021S0503933&GENDERlist=1&HEADERlist=0&Lang=E&STATISTIClist=1",
        "confidence": "high",
        "notes": "Median after-tax household income in 2020 for Vancouver CMA.",
    },
    {
        "market_key": "victoria_bc",
        "metric_key": "population",
        "value_numeric": 397237,
        "unit": "people",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/as-sa/fogs-spg/page.cfm?dguid=2021S0503935&lang=E&topic=1",
        "confidence": "high",
        "notes": "Victoria CMA population in the 2021 Census.",
    },
    {
        "market_key": "victoria_bc",
        "metric_key": "population_growth_percent",
        "value_numeric": 8.0,
        "unit": "percent",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/as-sa/fogs-spg/page.cfm?dguid=2021S0503935&lang=E&topic=1",
        "confidence": "high",
        "notes": "Population change from 2016 to 2021 for Victoria CMA.",
    },
    {
        "market_key": "victoria_bc",
        "metric_key": "unemployment_rate_percent",
        "value_numeric": 6.9,
        "unit": "percent",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/as-sa/fogs-spg/page.cfm?dguid=2021S0503935&lang=E&topic=12",
        "confidence": "medium",
        "notes": "Census unemployment rate for the population aged 15+ in Victoria CMA. This is not the same as the monthly Labour Force Survey series.",
    },
    {
        "market_key": "victoria_bc",
        "metric_key": "median_household_income",
        "value_numeric": 75500,
        "unit": "cad",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/as-sa/fogs-spg/Page.cfm?dguid=2021S0503935&lang=e&topic=5",
        "confidence": "high",
        "notes": "Median after-tax household income in 2020 for Victoria CMA.",
    },
    {
        "market_key": "duncan_bc",
        "metric_key": "population",
        "value_numeric": 47582,
        "unit": "people",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/as-sa/fogs-spg/Page.cfm?dguid=2021S0504937&lang=E&topic=1",
        "confidence": "high",
        "notes": "Duncan CA population in the 2021 Census.",
    },
    {
        "market_key": "duncan_bc",
        "metric_key": "population_growth_percent",
        "value_numeric": 7.0,
        "unit": "percent",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/as-sa/fogs-spg/Page.cfm?dguid=2021S0504937&lang=E&topic=1",
        "confidence": "high",
        "notes": "Population change from 2016 to 2021 for Duncan CA.",
    },
    {
        "market_key": "duncan_bc",
        "metric_key": "unemployment_rate_percent",
        "value_numeric": 7.5,
        "unit": "percent",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/as-sa/fogs-spg/page.cfm?dguid=2021S0504937&lang=E&topic=12",
        "confidence": "medium",
        "notes": "Census unemployment rate for the population aged 15+ in Duncan CA.",
    },
    {
        "market_key": "duncan_bc",
        "metric_key": "median_household_income",
        "value_numeric": 69000,
        "unit": "cad",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/as-sa/fogs-spg/page.cfm?dguid=2021S0504937&lang=E&topic=5",
        "confidence": "high",
        "notes": "Median after-tax household income in 2020 for Duncan CA.",
    },
    {
        "market_key": "sidney_bc",
        "metric_key": "population",
        "value_numeric": 12318,
        "unit": "people",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/details/page.cfm?DGUIDlist=2021A00055917010&GENDERlist=1&HEADERlist=0&Lang=E&STATISTIClist=1&SearchText=sidney",
        "confidence": "high",
        "notes": "Sidney town population in the 2021 Census.",
    },
    {
        "market_key": "sidney_bc",
        "metric_key": "population_growth_percent",
        "value_numeric": 5.5,
        "unit": "percent",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/details/page.cfm?DGUIDlist=2021A00055917010&GENDERlist=1&HEADERlist=0&Lang=E&STATISTIClist=1&SearchText=sidney",
        "confidence": "high",
        "notes": "Population change from 2016 to 2021 for the Town of Sidney.",
    },
    {
        "market_key": "sidney_bc",
        "metric_key": "unemployment_rate_percent",
        "value_numeric": 4.7,
        "unit": "percent",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/details/page.cfm?DGUIDlist=2021A00055917010%2C2021A000259&GENDERlist=1&HEADERlist=0&Lang=E&STATISTIClist=1&SearchText=British+Columbia",
        "confidence": "medium",
        "notes": "Census unemployment rate for the population aged 15+ in the Town of Sidney.",
    },
    {
        "market_key": "sidney_bc",
        "metric_key": "median_household_income",
        "value_numeric": 68500,
        "unit": "cad",
        "source_name": "Statistics Canada 2021 Census",
        "source_url": "https://www12.statcan.gc.ca/census-recensement/2021/dp-pd/prof/details/page.cfm?DGUIDlist=2021A00055917010%2C2021A000011124%2C2021A000212&GENDERlist=1%2C2%2C3&HEADERlist=0&Lang=e&STATISTIClist=1%2C4&SearchText=Sidney",
        "confidence": "high",
        "notes": "Median after-tax household income in 2020 for the Town of Sidney.",
    },
]


MARKET_METRIC_SERIES: list[dict[str, Any]] = [
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2017-01-01",
        "value_numeric": 95.1,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2017-04-01",
        "value_numeric": 100.2,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2017-07-01",
        "value_numeric": 102.5,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2017-10-01",
        "value_numeric": 102.1,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2018-01-01",
        "value_numeric": 104.7,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2018-04-01",
        "value_numeric": 107.8,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2018-07-01",
        "value_numeric": 107.5,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2018-10-01",
        "value_numeric": 108.2,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2019-01-01",
        "value_numeric": 106.3,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2019-04-01",
        "value_numeric": 109.4,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2019-07-01",
        "value_numeric": 108.6,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2019-10-01",
        "value_numeric": 111.0,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2020-01-01",
        "value_numeric": 111.5,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2020-04-01",
        "value_numeric": 112.0,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2020-07-01",
        "value_numeric": 113.9,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
    {
        "market_key": "victoria_bc",
        "series_key": "residential_property_price_index_total",
        "point_date": "2020-10-01",
        "value_numeric": 118.3,
        "unit": "index_2017_100",
        "source_name": "Statistics Canada RPPI",
        "source_url": "https://www150.statcan.gc.ca/n1/daily-quotidien/210208/cg-b007-png-eng.htm",
        "confidence": "high",
        "notes": "Statistics Canada residential property price index for Victoria, total series.",
    },
]


def get_market_seed_bundle(market_key: str) -> dict[str, Any] | None:
    profile = next((row for row in MARKET_PROFILES if row["market_key"] == market_key), None)
    if profile is None:
        return None
    metrics = [row for row in MARKET_METRICS if row["market_key"] == market_key]
    series = [row for row in MARKET_METRIC_SERIES if row["market_key"] == market_key]
    return {
        "profile": profile,
        "metrics": metrics,
        "series": series,
    }
