create table if not exists public.hpi_observations (
    id bigint generated by default as identity primary key,
    source text not null,
    market_key text not null references public.market_profiles(market_key) on delete cascade,
    market_name text not null,
    province text,
    property_type_slug text not null,
    property_type_label text not null,
    point_date date not null,
    year integer not null,
    month integer not null,
    index_value numeric,
    benchmark_price numeric,
    seasonal_adjustment text not null,
    source_file_name text,
    raw_payload jsonb not null default '{}'::jsonb,
    ingested_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, market_key, property_type_slug, point_date, seasonal_adjustment)
);

create table if not exists public.hpi_market_metrics (
    id bigint generated by default as identity primary key,
    source text not null,
    market_key text not null references public.market_profiles(market_key) on delete cascade,
    market_name text not null,
    province text,
    property_type_slug text not null,
    property_type_label text not null,
    latest_date date,
    latest_index_value numeric,
    latest_benchmark_price numeric,
    appreciation_5y_total_pct numeric,
    appreciation_5y_cagr numeric,
    appreciation_10y_total_pct numeric,
    appreciation_10y_cagr numeric,
    change_12m_pct numeric,
    change_3m_pct numeric,
    change_3m_annualized_pct numeric,
    change_1m_pct numeric,
    trend_direction text,
    data_quality_flag text,
    observation_count integer,
    method_notes text,
    raw_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, market_key, property_type_slug)
);

create index if not exists hpi_observations_lookup_idx
on public.hpi_observations(source, market_key, property_type_slug, point_date desc);

create index if not exists hpi_market_metrics_lookup_idx
on public.hpi_market_metrics(source, market_key, property_type_slug);

drop trigger if exists hpi_observations_set_updated_at on public.hpi_observations;
create trigger hpi_observations_set_updated_at
before update on public.hpi_observations
for each row
execute function public.set_updated_at();

drop trigger if exists hpi_market_metrics_set_updated_at on public.hpi_market_metrics;
create trigger hpi_market_metrics_set_updated_at
before update on public.hpi_market_metrics
for each row
execute function public.set_updated_at();
